test_data = [
    {
        "reference_id": "ref001",
        "author": "John Doe",
        "title": "An Innovative Approach to AI",
        "booktitle": "Proceedings of the AI Conference",
        "year": 2024,
        "editor": "Jane Smith",
        "volume": 1,
        "number": 1,
        "series": "AI Series",
        "pages": "1-10",
        "address": "New York, NY",
        "month": "November",
        "organization": "AI Society",
        "publisher": "Tech Press",
    },
    {
        "reference_id": "ref002",
        "author": "Alice Brown",
        "title": "Deep Learning Revolution",
        "booktitle": "Neural Networks Symposium",
        "year": 2023,
        "editor": None,
        "volume": 2,
        "number": None,
        "series": "Machine Learning Series",
        "pages": "50-60",
        "address": "San Francisco, CA",
        "month": "May",
        "organization": "ML Guild",
        "publisher": "Innovate Publishing",
    },
    {
        "reference_id": "ref003",
        "author": "Chris Green",
        "title": "Advances in Quantum Computing",
        "booktitle": "Quantum Tech Conference",
        "year": 2025,
        "editor": "Michael White",
        "volume": None,
        "number": None,
        "series": None,
        "pages": "101-110",
        "address": "Boston, MA",
        "month": "July",
        "organization": "Quantum League",
        "publisher": "Future Press",
    },
    {
        "reference_id": "ref004",
        "author": "Emma Wilson",
        "title": "Blockchain Beyond Cryptocurrencies",
        "booktitle": "Decentralized Systems Forum",
        "year": 2022,
        "editor": "Liam Brown",
        "volume": 3,
        "number": 2,
        "series": "Tech Frontiers",
        "pages": "20-30",
        "address": "London, UK",
        "month": "September",
        "organization": "Blockchain Alliance",
        "publisher": "Global Tech",
    },
    {
        "reference_id": "ref005",
        "author": "David Miller",
        "title": "Next-Gen Mobile Networks",
        "booktitle": "Telecom Innovations Summit",
        "year": 2023,
        "editor": None,
        "volume": None,
        "number": None,
        "series": "Connectivity Series",
        "pages": "75-85",
        "address": "Berlin, Germany",
        "month": "March",
        "organization": "5G Consortium",
        "publisher": "FutureComm",
    },
    {
        "reference_id": "ref006",
        "author": "Sophia Lopez",
        "title": "AI for Environmental Sustainability",
        "booktitle": "EcoTech Conference",
        "year": 2024,
        "editor": "Olivia Johnson",
        "volume": None,
        "number": None,
        "series": None,
        "pages": "40-50",
        "address": "Tokyo, Japan",
        "month": "April",
        "organization": "GreenTech Initiative",
        "publisher": "EcoPublish",
    },
    {
        "reference_id": "ref007",
        "author": "Michael Brown",
        "title": "Cybersecurity in IoT",
        "booktitle": "SecureTech Summit",
        "year": 2023,
        "editor": None,
        "volume": 5,
        "number": 3,
        "series": "IoT Security",
        "pages": "150-160",
        "address": "Singapore",
        "month": "June",
        "organization": "Cyber Alliance",
        "publisher": "Security World",
    },
    {
        "reference_id": "ref008",
        "author": "Emily Davis",
        "title": "Revolutionizing Healthcare with AI",
        "booktitle": "HealthTech Symposium",
        "year": 2025,
        "editor": "Daniel Garcia",
        "volume": 6,
        "number": None,
        "series": "HealthTech Innovations",
        "pages": "10-20",
        "address": "Paris, France",
        "month": "January",
        "organization": "Healthcare AI",
        "publisher": "MedTech Press",
    },
    {
        "reference_id": "ref009",
        "author": "James Taylor",
        "title": "Augmented Reality in Education",
        "booktitle": "EdTech Conference",
        "year": 2023,
        "editor": "Victoria Lee",
        "volume": None,
        "number": 4,
        "series": None,
        "pages": "200-210",
        "address": "Toronto, Canada",
        "month": "October",
        "organization": "EdTech Global",
        "publisher": "Learning Press",
    },
    {
        "reference_id": "ref010",
        "author": "Olivia Martin",
        "title": "Ethics in Artificial Intelligence",
        "booktitle": "AI Ethics Workshop",
        "year": 2024,
        "editor": None,
        "volume": 7,
        "number": 5,
        "series": "AI Responsibility",
        "pages": "300-310",
        "address": "Sydney, Australia",
        "month": "December",
        "organization": "AI Ethics Council",
        "publisher": "Moral AI",
    },
]
