
test_data = [
    {
        "reference_id": "ref01",
        "reference_type": "inproceedings",
        "title": "Advances in AI",
        "author": "Alice Johnson",
        "year": 2024,
        "publisher": None,
        "address": None,
        "journal": None,
        "volume": None,
        "number": None,
        "pages": None,
        "month": None,
        "note": None,
        "booktitle": "Proceedings of the AI Conference 2024",
        "editor": "-",
        "series": None,
        "organization": "AI Society"
    },
    {
        "reference_id": "ref02",
        "reference_type": "article",
        "title": "Deep Learning Insights",
        "author": "Bob Smith",
        "year": 2023,
        "publisher": "ML Publishers",
        "address": None,
        "journal": None,
        "volume": 12,
        "number": 3,
        "pages": None,
        "month": None,
        "note": None,
        "booktitle": None,
        "editor": None,
        "series": None,
        "organization": None
    },
    {
        "reference_id": "ref03",
        "reference_type": "book",
        "title": "Data Science Fundamentals",
        "author": "Clara White",
        "year": 2022,
        "publisher": "Tech Books",
        "address": None,
        "journal": None,
        "volume": None,
        "number": None,
        "pages": None,
        "month": None,
        "note": None,
        "booktitle": None,
        "editor": None,
        "series": None,
        "organization": None
    }
]
